### ISSUE TITLE
Cannot install yaml-front-matter

### ISSUE THREAD

**Issue by Glavin001** [dworthen/js-yaml-front-matter#2] opened 2015-01-02 03:48 UTC
```bash
$ npm install --save yaml-front-matter
npm ERR! Error: ENOENT, chmod '/Users/glavin/Documents/Project Dev/atom-beautify/node_modules/yaml-front-matter/node_modules/js-yaml/bin/js-yaml.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/glavin/.nvm/v0.10.32/bin/node" "/Users/glavin/.nvm/v0.10.32/bin/npm" "install" "--save" "yaml-front-matter"
npm ERR! cwd /Users/glavin/Documents/Project Dev/atom-beautify
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! path /Users/glavin/Documents/Project Dev/atom-beautify/node_modules/yaml-front-matter/node_modules/js-yaml/bin/js-yaml.js
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! error rolling back Error: Refusing to delete: /Users/glavin/Documents/Project Dev/atom-beautify/node_modules/.bin/js-yaml not in /Users/glavin/Documents/Project Dev/atom-beautify/node_modules/yaml-front-matter
npm ERR! error rolling back     at clobberFail (/Users/glavin/.nvm/v0.10.32/lib/node_modules/npm/lib/utils/gently-rm.js:57:12)
npm ERR! error rolling back     at next (/Users/glavin/.nvm/v0.10.32/lib/node_modules/npm/lib/utils/gently-rm.js:43:14)
npm ERR! error rolling back     at /Users/glavin/.nvm/v0.10.32/lib/node_modules/npm/lib/utils/gently-rm.js:52:12
npm ERR! error rolling back     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! error rolling back  { [Error: Refusing to delete: /Users/glavin/Documents/Project Dev/atom-beautify/node_modules/.bin/js-yaml not in /Users/glavin/Documents/Project Dev/atom-beautify/node_modules/yaml-front-matter]
npm ERR! error rolling back   code: 'EEXIST',
npm ERR! error rolling back   path: '/Users/glavin/Documents/Project Dev/atom-beautify/node_modules/.bin/js-yaml' }
npm ERR! not ok code 0
```

I think https://github.com/dworthen/js-yaml-front-matter/blob/master/package.json#L25 is the culprit and should be removed. 

I already have `js-yaml` as a dependency, so this conflict may be causing this problem in my case.

**Comment by Darkhogg** [comment] 2015-01-02 22:19
I also have this problem and I'm also using `js-yaml`.

**Comment by Glavin001** [comment] 2015-01-02 22:20
My solution was to remove the js-yaml dependency and every time I required js-yaml I would use this yaml front matter library (which just wraps js-yaml). 

—

**Comment by Darkhogg** [comment] 2015-01-02 22:22
I will try that, thank you.
I consider that a *workaround* and **not** a solution, though.

**Comment by Glavin001** [comment] 2015-01-02 22:23
Agreed, definitely a workaround. 

—

**Comment by razor-x** [comment] 2016-02-05 04:21
I also cannot install this (originally trying to install [html-brunch-static](https://github.com/bmatcuk/html-brunch-static)).

I believe it may be related to [npm v3 flatting](https://github.com/npm/npm/blob/master/CHANGELOG.md#flat-flat-flat) and [this line](https://github.com/dworthen/js-yaml-front-matter/blob/v3.3.0/package.json#L30) in `package.json`:

```
"bin": {
  ...
  "js-yaml": "node_modules/js-yaml/bin/js-yaml.js"
}
```

Since with npm 3 you can't assume `project-root/node_modules/yaml-front-matter/node_modules/js-yaml/bin/js-yaml.js` will exist. In general it will be promoted to `project-root/node_modules/js-yaml/bin/js-yaml.js`. Not sure why this package would take responsibility for claiming it's dependency's binary in `package.json` anyway.

**Comment by JStumpp** [comment] 2016-02-13 16:16
Same here. Removing the js-yaml from the package is a workaround. 
Could you remove the js-yaml from the package bin? It prevents installation on npm 3.

**Comment by thepont** [comment] 2016-02-15 03:59
I had the same issue, can be easily reproduced.

```
> mkdir test
> npm init -f
> npm install --save js-yaml
> npm install --save yaml-front-matter
```

**Comment by Wildhoney** [comment] 2016-02-15 20:21
Do we need [the `js-yaml` line](https://github.com/dworthen/js-yaml-front-matter/blob/master/package.json#L30) in the package.json? As far as I see, when `js-yaml` is installed it will install its own binary into the **node_modules/.bin** directory, therefore why does `js-yaml-front-matter` attempt to do the same?

https://github.com/thepont/js-yaml-front-matter/commit/6ae38fb05794eb1a1285e6f13151e91241de8d77 seems to have fixed this &mdash; let's get it merged! :+1:

**Closed** 2016-02-17 22:31 UTC
